<%
    // Close the try-block, which was opened in begin.jspf ...
    } catch (Throwable e) {
        // We are not interested in ServletExceptions, but in their cause ...
        while (e instanceof javax.servlet.ServletException) {
            javax.servlet.ServletException se = (javax.servlet.ServletException) e;
            if (se.getRootCause() != null) {
                e = se.getRootCause();
            } else {
                break;
            }
        }
        if (!com.aperto.webkit.debug.DontLogMeExceptionFilter.dontLog(e)) {
            String m = e.getMessage();
            m = "Caught " + e.getClass().getName() + (m == null ? "" : " (" + m + ")");
            // Log exception with debug info ...
            LOGGER.error(m+ "\n" + com.aperto.webkit.jsp.JspUtils.getDebugInfo(request), e);
            // Encapsulate e in a DontLogMeException, so it will not be logged again ...
            e = new com.aperto.webkit.debug.DontLogMeException(e);
        }
        // Throw e, so Tomcat will display the error page ...
        throw e;
    }
%>